"""Instagram screen signatures ordered by safety priority."""
from __future__ import annotations

from ..detector import ScreenDetector, ScreenSignature
from ..selectors import Selector
from .selectors import (
    ACCOUNT_SWITCHER,
    ACCOUNTS_CENTER_ALLOW,
    ACCOUNTS_CENTER_TITLE,
    ADD_ACCOUNT,
    ADD_PROFILE_PHOTO,
    ALLOW_LIMITED_PHOTOS,
    AVATAR_CROP_DONE,
    BIO_INPUT,
    BIRTH_DATE_INPUT,
    CHOOSE_FROM_LIBRARY,
    CONTINUE,
    CREATE_USERNAME_TITLE,
    DISPLAY_NAME_INPUT,
    FINAL_SIGNUP_SUBMIT,
    HOME,
    MEDIA_PERMISSION_MESSAGE,
    MEDIA_PICKER_CONFIRM,
    MEDIA_PICKER_PHOTO,
    PROFILE,
    SIGN_UP,
    SIGNUP_CONTACT_INPUT,
    TAKE_PHOTO,
    USERNAME_ENTRY_INPUT,
    USERNAME_INPUT,
    USERNAME_UNAVAILABLE_MARKER,
    USERNAME_VALID_MARKER,
)

PACKAGE = "com.instagram.android"
_PERMISSION_PACKAGE = "com.android.permissioncontroller"
_GOOGLE_PERMISSION_PACKAGE = "com.google.android.permissioncontroller"
_MEDIA_PICKER_PACKAGE = "com.google.android.providers.media.module"


def _text(semantic: str, *values: str) -> Selector:
    return Selector(semantic=semantic, texts=tuple(values))


def _protected(kind: str, semantic: str, *texts: str, priority: int) -> ScreenSignature:
    return ScreenSignature(kind, PACKAGE, (_text(semantic, *texts),), 1, 0.82, True, priority)


def build_instagram_detector() -> ScreenDetector:
    return ScreenDetector([
        _protected(
            "PASSWORD_REQUIRED",
            "password_marker",
            "Password",
            "Create a password",
            "Mật khẩu",
            priority=10,
        ),
        _protected(
            "OTP_REQUIRED",
            "otp_marker",
            "Enter confirmation code",
            "Enter code",
            "Verification code",
            "Mã xác nhận",
            "Mã xác minh",
            priority=11,
        ),
        _protected(
            "CAPTCHA_REQUIRED",
            "captcha_marker",
            "CAPTCHA",
            "I'm not a robot",
            "Verify you're human",
            priority=12,
        ),
        ScreenSignature(
            "IG_FINAL_SIGNUP_SUBMIT",
            PACKAGE,
            (
                FINAL_SIGNUP_SUBMIT,
                _text(
                    "signup_terms_marker",
                    "By signing up, you agree to our Terms",
                    "To sign up, read and agree to our terms and policies",
                    "Terms",
                    "Điều khoản",
                ),
            ),
            2,
            0.98,
            True,
            13,
        ),
        _protected(
            "EMAIL_OR_PHONE_VERIFICATION",
            "contact_verification",
            "Confirm your email",
            "Confirm your phone number",
            "Verify your email",
            "Verify your phone number",
            "Xác nhận email của bạn",
            "Xác nhận số điện thoại của bạn",
            priority=14,
        ),
        _protected(
            "SELFIE_OR_IDENTITY_CHECK",
            "identity_check",
            "Take a selfie",
            "Video selfie",
            "Confirm your identity",
            priority=15,
        ),
        _protected(
            "SECURITY_CHALLENGE",
            "security_challenge",
            "Security check",
            "Suspicious login attempt",
            "Help us confirm it's you",
            priority=16,
        ),
        _protected(
            "ACCOUNT_RECOVERY",
            "account_recovery",
            "Recover your account",
            "Account recovery",
            priority=17,
        ),
        _protected(
            "CONSENT_WITH_SECURITY_IMPACT",
            "security_consent",
            "Two-factor authentication",
            "Review security settings",
            priority=18,
        ),
        ScreenSignature(
            "NETWORK_ERROR",
            PACKAGE,
            (_text("network_error", "No internet connection", "Network error", "Couldn't refresh feed"),),
            1,
            0.95,
            False,
            30,
        ),
        ScreenSignature(
            "RATE_LIMITED",
            PACKAGE,
            (_text("rate_limited", "Try again later", "Please wait a few minutes"),),
            1,
            0.95,
            False,
            31,
        ),
        ScreenSignature(
            "ACTION_BLOCKED",
            PACKAGE,
            (_text("action_blocked", "Action blocked", "We restrict certain activity"),),
            1,
            0.95,
            False,
            32,
        ),
        ScreenSignature(
            "ACCOUNT_DISABLED",
            PACKAGE,
            (_text("account_disabled", "Your account has been disabled", "Account disabled"),),
            1,
            0.99,
            False,
            33,
        ),
        ScreenSignature(
            "APP_CRASH",
            "*",
            (_text("app_crash", "Instagram keeps stopping", "Instagram has stopped"),),
            1,
            0.99,
            False,
            34,
        ),
        ScreenSignature(
            "ANDROID_MEDIA_PERMISSION",
            _PERMISSION_PACKAGE,
            (MEDIA_PERMISSION_MESSAGE, ALLOW_LIMITED_PHOTOS),
            2,
            0.99,
            False,
            49,
        ),
        ScreenSignature(
            "ANDROID_MEDIA_PERMISSION",
            _GOOGLE_PERMISSION_PACKAGE,
            (MEDIA_PERMISSION_MESSAGE, ALLOW_LIMITED_PHOTOS),
            2,
            0.99,
            False,
            50,
        ),
        ScreenSignature(
            "ANDROID_MEDIA_PICKER",
            _MEDIA_PICKER_PACKAGE,
            (MEDIA_PICKER_PHOTO, MEDIA_PICKER_CONFIRM),
            2,
            0.99,
            False,
            51,
        ),
        ScreenSignature(
            "IG_AVATAR_SOURCE_MENU",
            PACKAGE,
            (CHOOSE_FROM_LIBRARY, TAKE_PHOTO),
            2,
            0.99,
            False,
            52,
        ),
        ScreenSignature(
            "IG_AVATAR_CROP",
            PACKAGE,
            (AVATAR_CROP_DONE,),
            1,
            0.99,
            False,
            53,
        ),
        ScreenSignature(
            "IG_ACCOUNT_SWITCHER",
            PACKAGE,
            (ADD_ACCOUNT,),
            1,
            0.98,
            False,
            58,
        ),
        ScreenSignature(
            "IG_EXISTING_PROFILE",
            PACKAGE,
            (PROFILE, ACCOUNT_SWITCHER),
            2,
            0.97,
            False,
            59,
        ),
        ScreenSignature("IG_POSTCHECK_OK", PACKAGE, (HOME, PROFILE), 2, 0.99, False, 60),
        ScreenSignature(
            "IG_ACCOUNTS_CENTER_CONSENT",
            PACKAGE,
            (ACCOUNTS_CENTER_TITLE, ACCOUNTS_CENTER_ALLOW),
            2,
            0.99,
            False,
            73,
        ),
        ScreenSignature(
            "IG_USERNAME_UNAVAILABLE",
            PACKAGE,
            (CREATE_USERNAME_TITLE, USERNAME_ENTRY_INPUT, USERNAME_UNAVAILABLE_MARKER),
            3,
            0.99,
            False,
            74,
        ),
        ScreenSignature(
            "IG_USERNAME_VALID",
            PACKAGE,
            (CREATE_USERNAME_TITLE, USERNAME_ENTRY_INPUT, USERNAME_VALID_MARKER, CONTINUE),
            4,
            0.99,
            False,
            75,
        ),
        ScreenSignature(
            "IG_USERNAME_ENTRY",
            PACKAGE,
            (CREATE_USERNAME_TITLE, USERNAME_ENTRY_INPUT, CONTINUE),
            3,
            0.97,
            False,
            76,
        ),
        ScreenSignature(
            "IG_AVATAR_SETUP",
            PACKAGE,
            (ADD_PROFILE_PHOTO,),
            1,
            0.96,
            False,
            77,
        ),
        ScreenSignature(
            "IG_BIRTHDAY_ENTRY",
            PACKAGE,
            (BIRTH_DATE_INPUT, CONTINUE),
            2,
            0.96,
            False,
            78,
        ),
        ScreenSignature(
            "IG_CONTACT_ENTRY",
            PACKAGE,
            (SIGNUP_CONTACT_INPUT, CONTINUE),
            2,
            0.96,
            False,
            79,
        ),
        ScreenSignature(
            "IG_PROFILE_SETUP",
            PACKAGE,
            (USERNAME_INPUT, DISPLAY_NAME_INPUT, BIO_INPUT, CONTINUE),
            2,
            0.96,
            False,
            80,
        ),
        ScreenSignature("IG_SIGNUP_ENTRY", PACKAGE, (SIGN_UP,), 1, 0.94, False, 81),
        ScreenSignature("IG_HOME", PACKAGE, (HOME,), 1, 0.96, False, 82),
    ])
