from enum import StrEnum


class BatchStatus(StrEnum):
    DRAFT = "DRAFT"
    READY = "READY"
    RUNNING = "RUNNING"
    PAUSED = "PAUSED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class RunnerType(StrEnum):
    LOCAL_DEVICE = "LOCAL_DEVICE"
    REMOTE_AVD = "REMOTE_AVD"


class AccountStage(StrEnum):
    NEW = "NEW"
    PROFILE_READY = "PROFILE_READY"
    # AVD_ASSIGNED remains readable for persisted P0 rows. New leases use the
    # runner-neutral RUNNER_ASSIGNED stage.
    AVD_ASSIGNED = "AVD_ASSIGNED"
    RUNNER_ASSIGNED = "RUNNER_ASSIGNED"
    IG_READY_FOR_HUMAN = "IG_READY_FOR_HUMAN"
    WAITING_HUMAN = "WAITING_HUMAN"
    NEEDS_VERIFICATION = "NEEDS_VERIFICATION"
    NEEDS_CONFIRMATION = "NEEDS_CONFIRMATION"
    USERNAME_UNAVAILABLE = "USERNAME_UNAVAILABLE"
    IG_CREATED = "IG_CREATED"
    THREADS_READY_FOR_HUMAN = "THREADS_READY_FOR_HUMAN"
    THREADS_CREATED = "THREADS_CREATED"
    ACP_CONNECTING = "ACP_CONNECTING"
    ACP_ACTIVE = "ACP_ACTIVE"
    COOLDOWN = "COOLDOWN"
    RETRY_PENDING = "RETRY_PENDING"
    ERROR = "ERROR"
    DISABLED = "DISABLED"


class WorkerState(StrEnum):
    STOPPED = "STOPPED"
    STARTING = "STARTING"
    READY = "READY"
    RUNNING = "RUNNING"
    WAITING_HUMAN = "WAITING_HUMAN"
    RECOVERING = "RECOVERING"
    DRAINING = "DRAINING"
    ERROR = "ERROR"
